[versions]

[libraries.firebase-config]
version = "19.2.0"
module = "com.google.firebase:firebase-config-ktx"

[libraries.firebase-analytics]
version = "17.5.0"
module = "com.google.firebase:firebase-analytics-ktx"

[libraries.firebase-crashlytics-gradle]
version = "2.3.0"
module = "com.google.firebase:firebase-crashlytics-gradle"
