[versions]
ack = "0.4.0"
kimchi-core = "1.1.0"
kimchi-firebase = "1.2.0"
watermelon = "0.3.0"

[libraries.kimchi-logger]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:logger"

[libraries.kimchi-core]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:core"

[libraries.kimchi-analytics]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:analytics"

[libraries.kimchi-firebase-crashlytics]
version.ref = "kimchi-firebase"
module = "com.github.inkapplications.kimchi-firebase-bridge:crashlytics"

[libraries.kimchi-firebase-analytics]
version.ref = "kimchi-firebase"
module = "com.github.inkapplications.kimchi-firebase-bridge:analytics"

[libraries.ack-codec]
version.ref = "ack"
module = "com.inkapplications.ack:codec"

[libraries.ack-client]
version.ref = "ack"
module = "com.inkapplications.ack:client"

[libraries.ack-structures]
version.ref = "ack"
module = "com.inkapplications.ack:structures"

[libraries.spondee-measures]
version = "0.5.0"
module = "com.inkapplications.spondee:measures"

[libraries.watermelon-coroutines]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:coroutines"

[libraries.watermelon-standard]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:standard"

[libraries.watermelon-android]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:android"
