[versions]
ack = "1.0.0"
kimchi-core = "2.1.1"
kimchi-firebase = "2.0.0-beta"
watermelon = "1.3.0"

[libraries.kimchi-logger]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:logger"

[libraries.kimchi-core]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:core"

[libraries.kimchi-analytics]
version.ref = "kimchi-core"
module = "com.inkapplications.kimchi:analytics"

[libraries.kimchi-firebase-crashlytics]
version.ref = "kimchi-firebase"
module = "com.inkapplications.kimchi-firebase:crashlytics"

[libraries.kimchi-firebase-analytics]
version.ref = "kimchi-firebase"
module = "com.inkapplications.kimchi-firebase:analytics"

[libraries.ack-codec]
version.ref = "ack"
module = "com.inkapplications.ack:codec"

[libraries.ack-client]
version.ref = "ack"
module = "com.inkapplications.ack:client"

[libraries.ack-structures]
version.ref = "ack"
module = "com.inkapplications.ack:structures"

[libraries.spondee-units]
version = "1.2.0"
module = "com.inkapplications.spondee:units"

[libraries.watermelon-coroutines]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:coroutines"

[libraries.watermelon-standard]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:standard"

[libraries.watermelon-android]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:android"

[bundles]
watermelon = [
    "watermelon-coroutines",
    "watermelon-standard",
    "watermelon-android",
]
