name: Pull Request
on: [pull_request]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.1
            -
                name: Unit Tests
                run: ./gradlew build jvmTest
