on:
  push:
    tags: ['*']
name: Release
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4.2.1
            -
                name: Configure Java
                uses: actions/setup-java@v4.3.0
                with:
                    java-version: 17
                    distribution: oracle
            -
                name: Keystore Setup
                run: echo "${{secrets.ANDROID_KEYSTORE_64}}" | base64 --decode > ack_upload.keystore
            -
                name: Google Services Setup
                run: echo '${{secrets.GOOGLE_SERVICES_JSON}}' > android-application/google-services.json
            -
                env:
                    ORG_GRADLE_PROJECT_signingFile: ack_upload.keystore
                    ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingAlias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
                    ORG_GRADLE_PROJECT_mapboxPrivate: ${{ secrets.MAPBOX_KEY_PRIVATE }}
                    ORG_GRADLE_PROJECT_mapboxPublic: ${{ secrets.MAPBOX_KEY_PUBLIC }}
                name: Build
                run: ./gradlew check assembleRelease bundleRelease -Pcommit=${{ github.sha }} -PversionName=${{ github.ref_name }} -PversionCode=$((($GITHUB_RUN_NUMBER * 10) + $GITHUB_RUN_ATTEMPT))
            -
                name: Prepare Uploads
                run: |
                    mkdir -p build
                    mkdir -p build/output
                    cp android-application/build/outputs/apk/functional/release/android-application-functional-release.apk build/output/Ack-${{ github.sha }}.apk
                    cp android-application/build/outputs/bundle/functionalRelease/android-application-functional-release.aab build/output/Ack-${{ github.sha }}.aab
            -
                name: Archive APK
                uses: actions/upload-artifact@v4.4.0
                with:
                    name: Android APK
                    path: build/output/Ack-${{ github.ref_name }}.apk
            -
                name: Archive Bundle
                uses: actions/upload-artifact@v4.4.0
                with:
                    name: Android AAB
                    path: build/output/Ack-${{ github.ref_name }}.aab
            -
                name: Service Account Setup
                run: echo '${{secrets.PLAY_CONSOLE_SERVICE_JSON}}' > service_account.json
            -
                name: Create Release
                id: create_release
                uses: actions/create-release@v1.1.4
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: ${{ github.ref_name }}
                    draft: true
                    prerelease: false
            -
                name: Upload AAB Release Asset
                uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: build/output/Ack-${{ github.ref_name }}.aab
                    asset_name: Ack-${{ github.ref_name }}.aab
                    asset_content_type: application/octet-stream
            -
                name: Upload APK Release Asset
                uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: build/output/Ack-${{ github.ref_name }}.apk
                    asset_name: Ack-${{ github.ref_name }}.apk
                    asset_content_type: application/octet-stream
            -
                name: Deploy to Play Store
                uses: r0adkll/upload-google-play@v1.1.3
                with:
                    serviceAccountJson: service_account.json
                    packageName: com.inkapplications.ack.android
                    releaseFile: build/output/Ack-${{ github.ref_name }}.aab
                    track: internal
