name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.4.0
            -
                name: Google Services Setup
                run: echo '${{secrets.GOOGLE_SERVICES_JSON}}' > android-application/google-services.json
            -
                env:
                    ORG_GRADLE_PROJECT_mapboxPrivate: ${{ secrets.MAPBOX_KEY_PRIVATE }}
                    ORG_GRADLE_PROJECT_mapboxPublic: ${{ secrets.MAPBOX_KEY_PUBLIC }}
                name: Build
                run: ./gradlew build test testDebugUnitTest bundleRelease -Psnapshot=true -PversionName=${{ github.sha }} -PversionCode=1
            -
                name: Prepare Uploads
                run: |
                    mkdir -p build
                    mkdir -p build/output
                    cp android-application/build/outputs/apk/release/android-application-release.apk build/output/Ack-${{ github.sha }}.apk
                    cp android-application/build/outputs/bundle/release/android-application-release.aab build/output/Ack-${{ github.sha }}.aab
            -
                name: Archive APK
                uses: actions/upload-artifact@v2.3.1
                with:
                    name: Android APK
                    path: build/output/Ack-${{ github.sha }}.apk
                    retention-days: 15
            -
                name: Archive Bundle
                uses: actions/upload-artifact@v2.3.1
                with:
                    name: Android AAB
                    path: build/output/Ack-${{ github.sha }}.aab
                    retention-days: 15
