name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.1
            -
                name: Keystore Setup
                run: echo "${{secrets.KEYSTORE}}" | base64 --decode > ack_upload.keystore
            -
                env:
                    ORG_GRADLE_PROJECT_signingFile: ack_upload.keystore
                    ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingAlias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
                    ORG_GRADLE_PROJECT_versionName: ${GITHUB_SHA:0:8}
                    ORG_GRADLE_PROJECT_versionCode: 1
                name: Build
                run: ./gradlew build jvmTest bundleRelease
            -
                name: Prepare Uploads
                run: |
                    mkdir build
                    mkdir build/output
                    cp android-application/build/outputs/apk/release/android-application-release.apk build/output/Ack-${{env.ORG_GRADLE_PROJECT_versionName}}.apk
                    cp android-application/build/outputs/bundle/release/android-application-release.aab build/output/Ack-${{env.ORG_GRADLE_PROJECT_versionName}}.aab
            -
                name: Archive APK
                uses: actions/upload-artifact@v2
                with:
                    name: Android APK
                    path: build/output/Ack-${{env.ORG_GRADLE_PROJECT_versionName}}.apk
                    retention-days: 15
            -
                name: Archive Bundle
                uses: actions/upload-artifact@v2
                with:
                    name: Android AAB
                    path: build/output/Ack-${{env.ORG_GRADLE_PROJECT_versionName}}.aab
                    retention-days: 15
